on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.6"
          channel: "stable"
      - name: Install packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test --coverage
      - name: Lint
        run: flutter analyze --no-pub --no-current-package lib test
